FROM python:3.10-slim

WORKDIR /app

COPY app_streamlit.py .
COPY modelos/ ./modelos/
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8503

CMD ["streamlit", "run", "app_streamlit.py", "--server.port=8503", "--server.address=0.0.0.0"]