version: "3.8"

services:
  api-inferencia:
    build:
      context: .
      dockerfile: Dockerfile  # Usa el Dockerfile actual con app_inferencia.py
    container_name: api-inferencia-locust
    ports:
      - "8000:8000"

  locust:
    build:
      context: .
      dockerfile: Dockerfile.locust
    container_name: locust
    ports:
      - "8089:8089"
    depends_on:
      - api-inferencia
    environment:
      - LOCUST_HOST=http://api-inferencia:8000
